"""initial schema

Revision ID: 3a660d785be3
Revises: 
Create Date: 2025-12-11 21:34:15.999365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a660d785be3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_statistics',
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('avg_pe_ratio', sa.Float(), nullable=True),
    sa.Column('avg_revenue_growth', sa.Float(), nullable=True),
    sa.Column('sum_revenue', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('industry')
    )
    op.create_table('raw_financial_data',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('income_data', sa.JSON(), nullable=True),
    sa.Column('balance_data', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('raw_general_data',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('general_data', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_raw_general_data_industry'), 'raw_general_data', ['industry'], unique=False)
    op.create_table('ticker_statistics',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('net_income_ttm', sa.Float(), nullable=True),
    sa.Column('debt_ratio', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticker_statistics')
    op.drop_index(op.f('ix_raw_general_data_industry'), table_name='raw_general_data')
    op.drop_table('raw_general_data')
    op.drop_table('raw_financial_data')
    op.drop_table('industry_statistics')
    # ### end Alembic commands ###
